online_retail:
  outputs:
    dev:
      dataset: retail 
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/<path to your service account file>
      location: US
      method: service-account
      priority: interactive
      project: <project id>
      threads: 1
      type: bigquery
  target: dev
